version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5433
    expose:
      - 5433
    env_file:
      - .env-docker
    ports:
      - 5433:5433

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5371
    expose:
      - 5371
    env_file:
      - .env-docker
    ports:
      - 5371:5371

  basic-app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: basic_app
    command: ["/fastapi/docker/basic_app.sh"]
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis

  inventory-app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: inventory_app
    command: [ "/fastapi/docker/inventory_app.sh" ]
    ports:
      - 8002:8002
    depends_on:
      - basic-app
      - db
      - redis
  bff-app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: bff_app
    command: [ "/fastapi/docker/bff_app.sh" ]
    ports:
      - 8003:8003
    depends_on:
      - basic-app
      - inventory-app
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: celery_app
    command: ["/fastapi/docker/celery.sh", "celery"]
    depends_on:
      - redis
  flower:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: flower_app
    command: ["/fastapi/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555